# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20160914_2153'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='itunes_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='directory.Itunes'),
            preserve_default=False,
        ),
    ]
