# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20160914_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
