# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20160914_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='date_time',
            new_name='time_published',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_time',
            new_name='time_published',
        ),
        migrations.AddField(
            model_name='feed',
            name='itunes_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='feed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_from_feed', to='feed.Feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='itunes_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='item',
            name='object_hash',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_itunes_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_managing_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_webmaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='lower_name',
            field=models.CharField(db_index=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_author', to='feed.Person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='enclosure_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itunes_duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='podcast_category', to='feed.PodcastCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('url', 'itunes_id')]),
        ),
        migrations.RemoveField(
            model_name='item',
            name='published_date',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('object_hash', 'time_published')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('lower_name', 'email')]),
        ),
    ]
