# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20160925_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='owner_name',
            new_name='owner',
        ),
    ]
