# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20160925_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_from_feed', to='feed.Feed'),
        ),
    ]
