# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20160925_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itunes_closed_caption',
            new_name='itunes_closed_captioned',
        ),
    ]
